CONFIDENCE_THRESHOLD = 0.6
DANGER_DISTANCE_CM = 100
WARNING_DISTANCE_CM = 50
ALERT_COOLDOWN_SEC = 3
CAMERA_INDEX = 0
SERIAL_PORT = "COM3"   # ← your actual port here
BAUD_RATE = 9600
MODEL_PATH = "models/yolov8n.pt"